url: http://whyiug.github.io
baseurl: ""
title: Ray
subtitle: Content-centric blogging
author: Young Ray
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: whyiug
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: Asia/Shanghai
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/github/whyiug.github.com/
# Pagination
paginate: 5
paginate_path: /page:num/

include: [_pages]

gems: [jekyll-paginate, jekyll-seo-tag]

# Comment

comments :
    provider : duoshuo
    duoshuo :
      short_name : bycode
    disqus :
      short_name : bycode
